### ISSUE TITLE
Problem in the ajax response when using the library

### ISSUE THREAD

**Issue by LouisCharles70** [mikechip/whatsapp-chatapi-sdk#2]
Hello,

This is the first time I experience this problem when using a php library, but when I use your library something is messing with my http response :

![image](https://user-images.githubusercontent.com/54309034/81264584-3b141780-9074-11ea-8b66-38332b9b66f2.png)

When I pass my data like this : 
        return response()->json([
            "unRepliedMessages" => $unRepliedMessages,
            "repliedMessages" => $repliedMessages
        ]);
It looks like this in the console :

![image](https://user-images.githubusercontent.com/54309034/81264732-82020d00-9074-11ea-8569-6e7930fc4be0.png)

**Comment by mikechip** [comment]
Kindly share more information about called functions and what they return. Are you trying to send message, I suppose?
